//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: chromatic_imap_dds.cpp
//  Source: chromatic_imap_dds.idl
//  Generated: Sun Jul 21 00:54:47 2013
//  OpenSplice V6.3.0OSS
//  
//******************************************************************

#include "chromatic_imap_dds_ext.h"

using namespace chromatic_imap_protocol_impl;
using namespace chromatic_imap_dds;


int main( int argc , char* argv[] )
{
	return 0;
}




