//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: chromatic_imap_dds.cpp
//  Source: chromatic_imap_dds.idl
//  Generated: Sat Jul 20 22:57:31 2013
//  OpenSplice V6.3.0OSS
//  
//******************************************************************

#include "chromatic_imap_dds.h"

int main( int argc , char* argv[] )
{
	return 0;
}




